- name: install cronie
  community.general.pacman:
    name:
      - cronie
    state: present
- name: ensure cronie is started and enabled at boot
  ansible.builtin.systemd:
    name: cronie
    state: started
    enabled: yes
