- name: install packages
  community.general.pakman:
    update_cache: yes
    name:
      - base-devel
      - bat
      - fd
      - fzf
      - git
      - htop
      - iotop
      - lm_sensors
      - man-db
      - man-pages
      - pacman-contrib
      - plocate
      - ripgrep
      - smartmontools
      - sudo
      - zsh
    state: present
- name: ensure plocate-updatedb.timer is starated and enabled at boot    
  ansible.builtin.systemd:
    name: plocate-updatedb.timer
    state: started
    enabled: yes
- name: symlink vi
  ansible.builtin.file:
    src: /usr/bin/vim
    dest: /usr/bin/vi
    state: link
- name: scripts directory
  ansible.builtin.file:
    path: /root/scripts
    state: directory
    owner: root
    group: root
    mode: "755"
- name: update pacman mirrors script
  ansible.builtin.copy:
    src: files/pacman-new-mirrorlist.sh
    dest: /root/scipts/pacman-new-mirrorlist.sh
    owner: root
    group: root
    mode: "755"
